// Generated by https://quicktype.io

export interface PopularMoviesListResponse {
    page: number;
    results: Movie[];
    total_pages: number;
    total_results: number;
}

export interface Movie {
    adult: boolean;
    backdrop_path: string;
    genre_ids: number[];
    id: number;
    original_language: OriginalLanguage;
    original_title: string;
    overview: string;
    popularity: number;
    poster_path: string;
    release_date: string;
    title: string;
    video: boolean;
    vote_average: number;
    vote_count: number;
}

export interface BillboarMovieListResponse {
    dates: Dates;
    page: number;
    results: Movie[];
    total_pages: number;
    total_results: number;
}

export interface Dates {
    maximum: string;
    minimum: string;
}


// Generated by https://quicktype.io

export interface ComingMoviesListResponse {
    dates: Dates;
    page: number;
    results: Movie[];
    total_pages: number;
    total_results: number;
}

export enum OriginalLanguage {
    Fr = "fr",
    Ja = "ja",
    En = "en",
    Es = "es",
    Pl = "pl",
    Hi = "hi"
}

// Generated by https://quicktype.io

export interface MovieCreditsResponse {
    cast: Movie[];
    crew: Movie[];
    id: number;
}